spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carzone
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:/Users/user/uploads
app:
  storage:
    location: C:/Users/user/uploads